name: "Custom Action"
description: "A simple JavaScript action"
inputs:
  currents-api-url:
    description: "Currents API URL"
    required: true
  run-id:
    description: "Cypress run id"
    required: true
  bearer-token:
    description: "Bearer authentication token"
    required: true
outputs:
  response-status-code: "HTTP Response status code"
runs:
  using: "node16"
  main: "dist/index.js"
