name: "Custom Action"
description: "A simple JavaScript action"
inputs:
  currents-api-url:
    description: "Currents API URL"
    required: false
    default: "https://api.currents.dev/api/v1"
  bearer-token:
    description: "Bearer authentication token"
    required: true
  github-run-id:
    description: "GitHub run id"
    required: true
  github-run-attempt:
    description: "GitHub run attempt"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
